name: fars
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.7
  - numpy
  - pandas
  - dask
  - pyjanitor
  - papermill
  - pathlib2
  - matplotlib
  - tqdm
  - seaborn
  - missingno
  - pooch
  - distributed
